### PR TITLE
Added some edits to imalsogreg's anti-hdf5 article.

### PR DESCRIPTION
**Pull request by jonnew**
This post is great. I started by doing some simple style, typo, spelling, and word-wrap edits.

### CODE REVIEW

**Comment by jonnew** [comment]
Just realized that my automatic word wrapper my have screwed up some of your code blocks. Lemme know which and I can fix.

**Comment by imalsogreg** [comment]
Of sweet, glad you think it's going well so far! It may be too late to switch now, but if you make two commits, the first for the spelling/style, and the second for word-wrap, then it's easier for me to see the style changes.

Also I like to make my editor word-wrap rather than have newlines in the document - makes stuff look nicer when it's in a web page. But I don't care much either way, if you like having newlines in the file while we edit.

I should warn you to take what I'm saying with a grain of salt. A lot of things that I sound certain about in the article are in reality things that I have to look into, to make sure I'm not missing how HDF5 actually works :P

**Comment by jonnew** [comment]
For some reason I don't get emails when ppl comment on my comments. Can I do that somehow?

Yeah, word wrapping all your pretty formatting was not very nice. Only reason to do word wrap outside editor is because one of markdown's charms is that it is readable outside something special to render it -- _not_ like HDF5 :). I will submit a new pull request for the spelling stuff.

With regard to preliminary nature -- yes, I understood the nascent feel of the post from the beginning. I think generally the points are very good, at least from my intuition/experience, but need to be solidified.

**Comment by imalsogreg** [comment]
Testing

**Pull request closed without merging**
